development:
  adapter: postgresql
  encoding: utf8
  database: bitcoin_transaction_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bitcoin_transaction_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: bitcoin_transaction_production
  pool: 5

